@startuml FastBite_State_Courier
title FastBite - Estados Operacionais do Estafeta (CourierStatus)

skinparam shadowing false

[*] --> OFFLINE

OFFLINE --> AVAILABLE : estafeta entra na app\ne ativa disponibilidade
AVAILABLE --> BUSY : estafeta aceita uma oferta\ne fica associado a uma entrega
BUSY --> AVAILABLE : entrega é concluída\ne o estafeta volta a receber ofertas
AVAILABLE --> OFFLINE : estafeta termina sessão\nou desliga a app
BUSY --> OFFLINE : socket é desligado
OFFLINE --> BUSY : recuperação excecional de entrega\njá atribuída



@enduml
