input SearchRestaurantsInput {
  q: String = ""
  name: String = ""
  chainName: String = ""
  city: String = ""
  country: String = ""
  postalCode: String = ""
  pageNumber: Int = 1
  pageSize: Int = 20
}

input CreateRestaurantChainInput {
  name: String!
}

input UpdateRestaurantChainInput {
  name: String
}

input SearchRestaurantChainsInput {
  q: String = ""
  pageNumber: Int = 1
  pageSize: Int = 20
}

input CreateRestaurantInput {
  chain_id: ID!
  name: String!
  opening_hours: String!
  closing_hours: String!
  delivery_radius: Float!
  street: String
  city: String
  postal_code: String
  country: String
  latitude: Float
  longitude: Float
}

input UpdateRestaurantInput {
  chain_id: ID
  name: String
  opening_hours: String
  closing_hours: String
  delivery_radius: Float
  street: String
  city: String
  postal_code: String
  country: String
  latitude: Float
  longitude: Float
}

extend type Query {
  searchRestaurants(input: SearchRestaurantsInput): [Restaurant!]!
    @field(resolver: "App\\GraphQL\\Queries\\RestaurantQueries@searchRestaurants")
  getRestaurantById(id: ID!): Restaurant
    @field(resolver: "App\\GraphQL\\Queries\\RestaurantQueries@getRestaurantById")
  searchRestaurantChains(input: SearchRestaurantChainsInput): [RestaurantChain!]!
    @field(resolver: "App\\GraphQL\\Queries\\RestaurantQueries@searchRestaurantChains")
  getRestaurantChainById(id: ID!): RestaurantChain
    @field(resolver: "App\\GraphQL\\Queries\\RestaurantQueries@getRestaurantChainById")
  getRestaurantsByChainId(chain_id: ID!): [Restaurant!]!
    @field(resolver: "App\\GraphQL\\Queries\\RestaurantQueries@getRestaurantsByChainId")
  getRestaurantByLocalManagerUserId(user_id: ID!): Restaurant
    @field(resolver: "App\\GraphQL\\Queries\\RestaurantQueries@getRestaurantByLocalManagerUserId")
  getRestaurantByManagerUserId(user_id: ID!): Restaurant
    @field(resolver: "App\\GraphQL\\Queries\\RestaurantQueries@getRestaurantByManagerUserId")
  getRestaurantsByManagerUserId(user_id: ID!): [Restaurant!]!
    @field(resolver: "App\\GraphQL\\Queries\\RestaurantQueries@getRestaurantsByManagerUserId")
  getRestaurantChainByManagerUserId(user_id: ID!): RestaurantChain
    @field(resolver: "App\\GraphQL\\Queries\\RestaurantQueries@getRestaurantChainByManagerUserId")
}

extend type Mutation {
  createRestaurantChain(input: CreateRestaurantChainInput!): RestaurantChain!
    @field(resolver: "App\\GraphQL\\Mutations\\RestaurantMutations@createRestaurantChain")
  updateRestaurantChain(id: ID!, input: UpdateRestaurantChainInput!): RestaurantChain!
    @field(resolver: "App\\GraphQL\\Mutations\\RestaurantMutations@updateRestaurantChain")
  deleteRestaurantChain(id: ID!): Boolean!
    @field(resolver: "App\\GraphQL\\Mutations\\RestaurantMutations@deleteRestaurantChain")

  createRestaurant(input: CreateRestaurantInput!): Restaurant!
    @field(resolver: "App\\GraphQL\\Mutations\\RestaurantMutations@createRestaurant")
  updateRestaurant(id: ID!, input: UpdateRestaurantInput!): Restaurant!
    @field(resolver: "App\\GraphQL\\Mutations\\RestaurantMutations@updateRestaurant")
  deleteRestaurant(id: ID!): Boolean!
    @field(resolver: "App\\GraphQL\\Mutations\\RestaurantMutations@deleteRestaurant")

  assignChainManager(user_id: ID!, chain_id: ID!): ChainManager!
    @field(resolver: "App\\GraphQL\\Mutations\\RestaurantMutations@assignChainManager")
  assignLocalManager(user_id: ID!, restaurant_id: ID!): LocalManager!
    @field(resolver: "App\\GraphQL\\Mutations\\RestaurantMutations@assignLocalManager")
}
