<?php

namespace App\Enums;

enum OutboxEventType: string
{
    case ORDER_CREATED = 'ORDER_CREATED';
    case ORDER_PAYMENT_COMPLETED = 'ORDER_PAYMENT_COMPLETED';
    case ORDER_CONFIRMED = 'ORDER_CONFIRMED';
    case ORDER_REJECTED = 'ORDER_REJECTED';
    case ORDER_COURIER_ASSIGNED = 'ORDER_COURIER_ASSIGNED';
    case ORDER_PREPARING = 'ORDER_PREPARING';
    case ORDER_READY = 'ORDER_READY';
    case ORDER_PICKED_UP = 'ORDER_PICKED_UP';
    case ORDER_OUT_FOR_DELIVERY = 'ORDER_OUT_FOR_DELIVERY';
    case ORDER_DELIVERED = 'ORDER_DELIVERED';
    case ORDER_CANCELLED = 'ORDER_CANCELLED';

    case PAYMENT_CREATED = 'PAYMENT_CREATED';
    case PAYMENT_COMPLETED = 'PAYMENT_COMPLETED';
    case PAYMENT_FAILED = 'PAYMENT_FAILED';
    case PAYMENT_EXPIRED = 'PAYMENT_EXPIRED';
    case PAYMENT_CANCELLED = 'PAYMENT_CANCELLED';
    case PAYMENT_REFUNDED = 'PAYMENT_REFUNDED';

    case DELIVERY_ACCEPTED = 'DELIVERY_ACCEPTED';
    case DELIVERY_PICKED_UP = 'DELIVERY_PICKED_UP';
    case DELIVERY_IN_TRANSIT = 'DELIVERY_IN_TRANSIT';
    case DELIVERY_DELIVERED = 'DELIVERY_DELIVERED';
    case DELIVERY_FAILED = 'DELIVERY_FAILED';

    case JOB_OFFERED = 'JOB_OFFERED';
    case JOB_ACCEPTED = 'JOB_ACCEPTED';
    case JOB_REJECTED = 'JOB_REJECTED';
    case JOB_EXPIRED = 'JOB_EXPIRED';

    case COURIER_POSITION_UPDATED = 'COURIER_POSITION_UPDATED';
    case CHAT_MESSAGE_SENT = 'CHAT_MESSAGE_SENT';
    case USER_NOTIFICATION_CREATED = 'USER_NOTIFICATION_CREATED';
}
